server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL 

    # path for about view
    path(route='about/', view=views.about, name="about"),
    # path for contact us view
    path(route='contact/', view=views.contact, name="contact"),
    # path for registration
    path(route='register/', view=views.registration_request, name="registration"),
    # path for login
    path(route='login/', view=views.login_request, name="login"),
    # path for logout
    path(route='logout/', view=views.logout_request, name="logout"),
    #path for index
    path(route='', view=views.get_dealerships, name='index'),
    path(route='<str:state>/', view=views.get_dealership_details, name='dealership_details'),

    # path for dealer reviews view
    path(route='dealer/<int:dealer_id>/', view=views.get_dealer_details, name='dealer_details'),
    # path for add a review view
    path(route='dealer/<int:dealer_id>/review/', view=views.add_review, name='add_review'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create models here.
# Car Make
class CarMake(models.Model):
    name = models.CharField(null=False, max_length=30)
    description = models.CharField(null=False, max_length=300)

    def __str__(self):
        return "Name: " + self.name + "\n" + \
                "Description: " + self.description

class CarModel(models.Model):

    sedan = 'Sedan'
    suv = 'SUV'
    wagon = 'WAGON'
    others = "Others"
    car_choices = [(sedan, 'Sedan'), (suv, 'SUV'), (wagon, 'WAGON'), (others, 'Others')]

    car_make = models.ForeignKey(CarMake, null=True, on_delete=models.CASCADE)
    name = models.CharField(null=False, max_length=30)
    dealer_id = models.IntegerField(null=True)
    car_type = models.CharField(null=False, max_length=30, choices=car_choices)
    year = models.DateField(null=True)

    def __str__(self):
        return "Name: " + self.name + "\n" + \
                "Type: " + self.car_type  


# <HINT> Create a plain Python class `CarDealer` to hold dealer data
class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, state, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer state
        self.state = state
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name

# <HINT> Create a plain Python class `DealerReview` to hold review data
class DealerReview:

    def __init__(self, name , dealership , review , purchase, purchase_date , car_make , car_model , car_year, sentiment):
        self.name = name
        self.dealership = dealership
        self.review = review
        self.purchase = purchase
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment

    def __str__(self):
        return "Review: " + self.review

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from dotenv import load_dotenv
from .models import CarModel
from . import restapis
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json
import os

load_dotenv()

WEB_ACTION_URL = os.getenv("WEB_ACTION_URL")

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request 
def login_request(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if request.META.get('HTTP_REFERER').find('/djangoapp/login/') == -1:
                return redirect(request.META.get('HTTP_REFERER'))
            elif request.META.get('HTTP_REFERER').find('/djangoapp/login/') != -1:
                return redirect('/djangoapp')
        else:
            return render(request, 'djangoapp/login.html', context)
    
    else:
        return render(request, 'djangoapp/login.html', context)


# Create a `logout_request` view to handle sign out request
def logout_request(request):
    logout(request)
    return redirect('/djangoapp')

# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == "POST":
        username = request.POST['username']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        password = request.POST['password']
        user_exist = False

        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            # If not, simply log this is a new user
            logger.debug("{} is new user".format(username))

        if not user_exist:
            # Create user in auth_user table
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password)
            # Login the user and redirect to course list page
            login(request, user)
            return redirect("/djangoapp/")
        else:
            return render(request, 'djangoapp/registration.html', context)

# The `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    context = {}
    if request.method == "GET":
        url = f"{WEB_ACTION_URL}/dealerships/get-dealership.json"
        # Get dealers from the URL
        context["dealerships"] = restapis.get_dealers_from_cf(url)
        # Concat all dealer's short name
        return render(request, 'djangoapp/index.html', context)

# The `get_dealerships_details` view to render the index page with a list of dealerships
def get_dealership_details(request, state):
    context = {}
    if request.method == "GET":
        url = f"{WEB_ACTION_URL}/dealerships/get-dealership.json"
        # Get dealers from the URL
        context["dealerships"] = restapis.get_dealers_by_state_from_cf(url, state)
        
        return render(request, 'djangoapp/index.html', context)

# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    context = {}
    if request.method == "GET":
        url = f"{WEB_ACTION_URL}/reviews/get-review.json"
        # Get dealers from the URL
        context["reviews"] = restapis.get_dealer_reviews_by_id_from_cf(url, dealer_id)

        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review
def add_review(request, dealer_id):
    if request.method == "GET": 
        url = f"{WEB_ACTION_URL}/dealerships/get-dealership.json?dealerId={dealer_id}"
        # Get dealers from the URL
        context = {
            "cars": CarModel.objects.all(),
            "dealer": restapis.get_dealers_from_cf(url)[0],
        }
        return render(request, 'djangoapp/add_review.html', context)

    if request.method == "POST":
        if request.user.is_authenticated:
            form = request.POST
            review = {
                "name": f"{request.user.first_name} {request.user.last_name}",
                "dealership": dealer_id,
                "review": form["content"],
                "purchase": False
            }
            if form.get("purchase_check"):
                review["purchase"]: True
                review["purchase_date"] = datetime.strftime(datetime.strptime(form.get("purchase_date"), "%m/%d/%Y"), "%m/%d/%Y")
                car = CarModel.objects.get(pk=form["car"])
                review["car_make"] = car.car_make.name
                review["car_model"] = car.name
                review["car_year"]= car.year.strftime("%Y")
            
            json_payload = {"review": review}
            url = f"{WEB_ACTION_URL}/reviews/post-review.json"
            restapis.post_request(url, json_payload, dealerId=dealer_id)
            return redirect("djangoapp:dealer_details", dealer_id=dealer_id)
        else:
            return redirect("/djangoapp/login")
                 

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
    <!--Add a registration form here -->
    <h1>About Page</h1>
    </body>
</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
    <body>
    <!--Add review form here -->
    <div class="container-sm d-flex align-items-center flex-column">
        <a class="navbar-brand text-uppercase display-1 font-weight-bold" style="font-size: 40px; color: #696969" href="/djangoapp/">Best cars</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="card w-50" style="min-width: 1200px">
            <form method="POST" action="/djangoapp/dealer/{{dealer.id}}/review/">
                {% csrf_token %}
                <h1 class="text-center m-2" for="add-review">Add a review about {{dealer.full_name}}</h1>
                <h5 class="ml-4">Enter the review content:</h5>
                <div class="form-group mx-4 my-2">
                    <textarea type="text" class="form-control" style="height: 100px" placeholder="Type here..." name="content" required></textarea>
                </div>
                <div class="form-group mx-4 my-2">
                    <input type="checkbox" onclick="togglePurchase()" placeholder="Password" name="purchase_check">
                    Has purchased the car from {{dealer.full_name}}? (select purchased car information below if checked)
                </div>
                <div id="purchase-check" style="display: none">
                    <div class="form-group mx-4 my-2">
                        <h5>Select your car (model-make-year):</h5>
                        <select name="car" id="car" class="form-select" required>
                            {% for car in cars %}
                                <option selected value={{car.id}}>{{car.name}}-{{car.car_make.name}}-{{ car.year|date:"Y" }}</option>
                            {% endfor %} 
                       </select>
                    </div>
                    <div class="form-group mx-4 my-2">
                        <h5>Select your purchase date:</h5>
                        <input type="text" class="date-own form-control w-25" name="purchase_date" id="purchase_date">
                    </div>
                </div>
                <div class="d-flex align-items-center flex-column m-4">
                    <button type="submit" class="btn btn-primary w-100">Submit</button>
                </div>
            </form>
        </div>            
    </div>
    </body>

    <script>
        function togglePurchase() {
            var check = document.getElementById("purchase-check");
            if(check.style.display === "none") {
                check.style.display = "block"
            } else {
                check.style.display = "none"
            }
        }
    </script>
</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
    <!--Add a registration form here -->
    <h1>Contact Page</h1>
    </body>
</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

    <body>

    <!--Add a nav bar here -->
    {% include 'navbar.html' %}
    <!-- Add reviews as cards -->
    {% if user.is_authenticated %}
        <a href="review/" class="d-flex justify-content-center text-decoration-none mt-4 h4">Add review</a>
        <div class="card-deck d-flex m-4 justify-content-center">
            {% for review in reviews %}
                <div class="card mt-4 ml-2" style="min-width: 240px; max-width: 240px">
                    <div class="card-body">
                        <img class="card-img-top" style="position: absolute; width: 24px; height: 24px; right: -10px; top: -10px" src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" alt="emoji">
                        <h5 class="card-title">
                            {{ review.name }}
                        </h5>
                        <p class="card-text">
                            {{ review.car_year }}
                        </p>
                        <p class="card-text">
                            <small class="text-muted">{{ review.review }}</small>
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="text-center m-5">Sorry! You need to login to add review.</h1>
    {% endif %}
    </body>

</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body>
    <!--Add a nav bar here -->
        {% include 'navbar.html' %}
        <form class="m-4">
            <div class="table-responsive-lg">
                <table class="table table-bordered">
                    <thead class="thead-light">
                    <tr>
                        <th style="width: 5%">#</th>
                        <th style="width: 30%">Name</th>
                        <th style="width: 15%">City</th>
                        <th style="width: 20%">Address</th>
                        <th style="width: 10%">Zip</th>
                        <th style="width: 20%">
                            <button class="btn dropdown-toggle" style="padding: 0; font-size: 16px; font-weight: 700; color: #495057" type="button" data-toggle="dropdown">
                                State
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" style="padding: 0px; width: 100px">
                                <input class="form-control" id="stateInput" type="text" placeholder="Search..">
                            </ul>
                        </th>
                    </tr>
                    </thead>
                    <tbody id="state">
                        {% for dealership in dealerships %}
                            <tr>
                                <td>{{ dealership.id }}</td>
                                <td>
                                    <a href="{% url 'djangoapp:dealer_details' dealership.id %}">{{dealership.full_name}}</a>
                                </td>
                                <td>{{ dealership.city }}</td>
                                <td>{{ dealership.address }}</td>
                                <td>{{ dealership.zip }}</td>
                                <td>{{ dealership.state }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>  
        </form>

    </body>

    <script>
        $(document).ready(function(){
          $("#stateInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#state tr").filter(function() {
              $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
          });
        });
    </script>
</html>

server/djangoapp/templates/djangoapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
        <div class="container-sm d-flex align-items-center flex-column">
            <a class="navbar-brand text-uppercase display-1 font-weight-bold" style="font-size: 40px; color: #696969" href="/djangoapp/">Best cars</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="card w-50" style="max-width: 400px">
                <form method="POST" action="{% url 'djangoapp:login' %}">
                    {% csrf_token %}
                    <h1 class="text-center m-4" for="login">Login</h1>
                    <div class="form-group mx-4 my-2">
                        <input type="text" class="form-control" placeholder="Username" name="username" required>
                    </div>
                    <div class="form-group mx-4 my-2">
                        <input type="password" class="form-control" placeholder="Password" name="password" required>
                    </div>
                    <div class="d-flex align-items-center flex-column m-4">
                        <button type="submit" class="btn btn-primary w-100">Login</button>
                    </div>
                    <hr class="w-75" />
                    <div class="d-flex align-items-center flex-column m-3">
                        <a href="/djangoapp/register/" type="submit" class="btn btn-link">Create new account</a>
                    </div>
                </form>
            </div>            
        </div>
    </body>
</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
        <div class="container-sm d-flex align-items-center flex-column">
            <a class="navbar-brand text-uppercase display-1 font-weight-bold" style="font-size: 40px; color: #696969" href="/djangoapp/">Best cars</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="card w-50" style="max-width: 400px">
                <form method="POST" action="{% url 'djangoapp:registration' %}">
                    {% csrf_token %}
                    <h1 class="text-center m-4" for="register">Sign Up</h1>
                    <div class="form-group d-flex flex-row mx-4 my-2">
                        <input type="text" class="form-control w-50" placeholder="First Name" name="firstname" required>
                        <input type="text" class="form-control w-50 ml-2" placeholder="Last Name" name="lastname" requried>
                    </div>
                    <div class="form-group mx-4 my-2">
                        <input type="text" class="form-control" placeholder="Username" name="username" requried>
                    </div>
                    <div class="form-group mx-4 my-2">
                        <input type="password" id="password" name="password" class="form-control" placeholder="Password" requried>
                    </div>
                    <div class="d-flex align-items-center flex-column m-4">
                        <button type="submit" class="btn btn-primary w-100">Sign Up</button>
                    </div>
                    <div class="d-flex align-items-center flex-column m-4">
                        <p class="m-0">Already have an account? </p>
                        <a href="/djangoapp/login/">Sign in</a>
                    </div>
                </form>
            </div>            
        </div>
    </body>
</html>